In [6]:
import numpy as np
A = np.array([
[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]],
])
print(A.shape)
B = np.max(A) # Find the maximum from all elements
# C = np.max(A, axis = 2) # Find the maximum elements from each dim2
D = np.max(A, axis = 1) # Find the maximum elements from each dim1
# E = np.max(A, axis = 0) # Find the maximum elements from each dim0
F = np.max(A, axis = (2,1))

# A2 = the maximum elements from each dim2 of A
# F = the maximum elements from each dim1 of A2

print(B)
# print(C)
print(D)
# print(E)
print(F)

(2, 2, 3)
12
[[ 4  5  6]
 [10 11 12]]
[ 6 12]


In [1]:
import numpy as np
images,channels,height,width = [2,3,2,3]
r,g,b = 1.0,0.5,0.8
A=np.empty((images,3,height,width))

# A[:,0]=r
print(A[:,0])
# print(A)
# A[:,1]=g
# print(A)
# A[:,2]=b
# print(A)
# B=A.reshape(images,3,height*width)
# print(B)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [19]:
a = [0,0,0,0,0]
print(a)
b = a[:] 
print(b)
b = [5]
print(b)

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[5]


In [8]:
import numpy as np
test1 = np.arange(1,21).reshape(10,-1)
up, down = np.split(test1, [7,1] )
print(up)
print(down)

ValueError: too many values to unpack (expected 2)

In [13]:
import pandas as pd
request_url = "https://www.imdb.com/chart/top"
html_tables = pd.read_html(request_url)
print(type(html_tables))
print(len(html_tables))
html_tables[0]

<class 'list'>
1


Unnamed: 0              Rank & Title  IMDb Rating  \
0           NaN        1.  刺激1995  (1994)          9.2   
1           NaN            2.  教父  (1972)          9.1   
2           NaN         3.  教父第二集  (1974)          9.0   
3           NaN          4.  黑暗騎士  (2008)          9.0   
4           NaN          5.  十二怒漢  (1957)          8.9   
..          ...                       ...          ...   
245         NaN      246.  阿爾及爾之戰  (1966)          8.0   
246         NaN      247.  卡比莉亞之夜  (1957)          8.0   
247         NaN        248.  公主新娘  (1987)          8.0   
248         NaN       249.  巴黎，德州  (1984)          8.0   
249         NaN  250.  Drishyam 2  (2021)          8.0   

                            Your Rating  Unnamed: 4  
0    12345678910 NOT YET RELEASED  Seen         NaN  
1    12345678910 NOT YET RELEASED  Seen         NaN  
2    12345678910 NOT YET RELEASED  Seen         NaN  
3    12345678910 NOT YET RELEASED  Seen         NaN  
4    12345678910 NOT YET RELEASED  Seen         NaN  
..                                  ...         ...  
245  12345678910 NOT YET RELEASED  Seen         NaN  
246  12345678910 NOT YET RELEASED  Seen         NaN  
247  12345678910 NOT YET RELEASED  Seen         NaN  
248  12345678910 NOT YET RELEASED  Seen         NaN  
249  12345678910 NOT YET RELEASED  Seen         NaN  

[250 rows x 5 columns]

In [17]:
from datetime import date
from datetime import timedelta
import urllib.error
def get_latest_daily_report():
    data_date = date.today()
    day_delta = timedelta(days=1)
    while True:
        data_date_str = date.strftime(data_date, '%m-%d-%Y')
        print("Try importing {} data...".format(data_date_str))
        daily_report_url = "https://raw.githubusercontent.com\
/CSSEGISandData/COVID-19/master\
/csse_covid_19_data/csse_covid_19_daily_reports/{}.csv".format(data_date_str)
        try:
            daily_report = pd.read_csv(daily_report_url)
            print("Successfully imported {} data!".format(data_date_str))
            break
        except urllib.error.HTTPError:
            data_date -= day_delta
    return daily_report

In [18]:
te = get_latest_daily_report()


Try importing 11-27-2021 data...
Try importing 11-26-2021 data...
Successfully imported 11-26-2021 data!


In [45]:
request_url = "https://www.imdb.com/chart/top"
html_tables = pd.read_html(request_url)
html_table = html_tables[0]
split_dataframe = html_table['Rank & Title'].str.split(expand=True)
ranks = split_dataframe[0].str.replace(".", '').values
years = split_dataframe[2].str.replace("\(|\)", '').values
titles = split_dataframe[1].values
ratings = html_table['IMDb Rating'].values
out = pd.DataFrame()
out['rank'] = ranks
out['title'] = titles
out['year'] = years
out['rating'] = ratings

<ipython-input-45-608fa4daf40b>:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  ranks = split_dataframe[0].str.replace(".", '').values
<ipython-input-45-608fa4daf40b>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  years = split_dataframe[2].str.replace("\(|\)", '').values


In [68]:
new = np.array(list(map(lambda x : int(x),ranks)))
print(ranks.nbytes,new.nbytes)

2000 1000
